// Generated by CoffeeScript 1.8.0
var async, cheerio, config, count, fileData, fs, request;

fs = require('fs');

async = require('async');

request = require('request');

cheerio = require('cheerio');

config = require('./config');

fileData = '# Style-Guidelines\ncollection of style guidelines\n\n';

count = 0;

async.whilst(function() {
  return count < config.length;
}, function(cb) {
  return request.get(config[count], function(error, response, body) {
    var $, title;
    if (error) {
      console.log(error);
      return;
    }
    $ = cheerio.load(body);
    title = $('title').text();
    if (title) {
      fileData += "[" + title + "](" + config[count] + ")\n\n";
    }
    count++;
    cb();
  });
}, function(err, data) {
  return fs.writeFile('README.MD', fileData, function(err) {
    if (err) {
      return console.log('write file error');
    } else {
      return console.log('file generated');
    }
  });
});

//# sourceMappingURL=index.js.map
